### ISSUE TITLE
Custom CSS does not hide warning

### ISSUE THREAD

**Issue by Bertie2011** [brunomnsilva/JavaFXSmartGraph#12]
I managed to set a custom properties file path using the Graph constructor (I think), which removed the missing properties file warning. The css file check is hardcoded, a style sheet parameter in SmartGraphPanel would prevent the missing default css file warning from being printed to console.

**Comment by brunomnsilva** [comment]
Can you elaborate?

You can use the `SmartGraphProperties(InputStream inputStream)` constructor that accepts a file stream and pass this object to the SmartGraphPanel constructor.

Otherwise, the provided (or custom/modified) `smartgraph.properties` file must be in the project's root folder.

**Comment by Bertie2011** [comment]
Sorry I put you on the wrong path there... I was using the properties as an example of what does go right, to illustrate why it's odd that the **CSS file warning** does not get hidden after adding a stylesheet myself.

**Comment by brunomnsilva** [comment]
Hm.. so everything is okay?

**Comment by Bertie2011** [comment]
No, let me explain again. I was wrong about the location of the CSS file check, which is why the suggested solution(s) were inaccurate and confusing.

The check for the default CSS file location happens inside the constructor (SmartGraphPanel, line 180), it would be nice if we could supply our own style sheet location. I'll update the original issue description as the suggested solution was inaccurate.

**Comment by brunomnsilva** [comment]
Previously:
I'm just a little confused, because there are two base files: the properties file and the stylesheet file. You are mentioning both at the same time.

The provided constructors only receive properties and not styling. The `smartgraph.css` must be present in the filepath. 

----

I see what you mean. I didn't see you were using `panel.getStylesheets().add(//my own uri)` directly.

Sorry for the CAPS, i was putting "----" :smile:

**Comment by Bertie2011** [comment]
Oh boy.... I'm just never going to talk about properties again in here haha

---
Let's focus on CSS stylesheets. I can set custom CSS using `SmartGraphPanel.getStylesheets().add(//uri)`

It would be nice to set my own file path for CSS without seeing the warning about missing style sheets every time I create the SmartGraphPanel.

**Comment by brunomnsilva** [comment]
Yeah, I see the problem. Let me check for a simple solution.

**Comment by brunomnsilva** [comment]
I've committed an update. Now you have an additional constructor `SmartGraphPanel(Graph<V, E> theGraph, SmartGraphProperties properties, SmartPlacementStrategy placementStrategy, URI cssFile)` that you can use directly and avoid the warning! :+1: 

Use `null` in the other arguments if you wish to use default values. This is described in the javadoc.

**Comment by Bertie2011** [comment]
Awesome!
You should try referencing the issue on the commit or PR in question. (Just add #xx with the issue number). It will show up in this thread and gives a nice confirmation.

**Comment by brunomnsilva** [comment]
Thanks for the tip, I'll start using it! :smile:
