### ISSUE TITLE
How to setup properties file ?

### ISSUE THREAD

**Issue by averroes96** [brunomnsilva/JavaFXSmartGraph#15]
I know this not really an issue but i've no idea how to setup the properties file on my project ! i managed to understand every point except for this one.

thanks in advance

**Comment by brunomnsilva** [comment]
Hi, @averroes96 .

What do you mean by "setup"? The (default) properties file must be in the project's "root" directly (similarly to the default CSS) or some implementing class passed in the constructor.

As for the parameters themselves, some are problem-specific are must be derived by trial-and-error.

**Comment by averroes96** [comment]
hi @brunomnsilva 

i'm using netbeans and i've no idea how to include these properties, i tried adding them to the `project.properties` file but nothing changed

**Comment by brunomnsilva** [comment]
Oh, I see.

**Just put the files in you Netbeans project root folder**. When you execute the project from Netbeans, that's where it will lookup those files.

If you later make a distributable JAR, then those files should be kept in the same folder as the JAR.

As for now, the library itself doesn't deal with those files being  packaged *resources*. But that can be done outside of the library easily.

**Comment by Ottokranz** [comment]
You can load the properties from resources as string and then use them:
`InputStream is = ClassLoader.getSystemClassLoader()
		.getResourceAsStream("resources/smartgraph.properties");
String propertieString = new BufferedReader(
		new InputStreamReader(is, StandardCharsets.UTF_8))
		.lines()
		.collect(Collectors.joining("\n"));
SmartGraphProperties properties = new SmartGraphProperties(propertieString);`
