### ISSUE TITLE
There's already a vertex with this element.

### ISSUE THREAD

**Issue by manzoorhussain1996** [brunomnsilva/JavaFXSmartGraph#17]
Hi 
Thank you for this beautiful graph library. However its is continuously throwing exception mention in above title. I am trying to show connected graphs. The vertex may be more than one in complex. Also I am adding the vertex dynamically. But After the loop run only onces the library throws this exception. Please have a look on this error. 
The error details looks like this:
com.brunomnsilva.smartgraph.graph.InvalidVertexException: There's already a vertex with this element.
	at com.brunomnsilva.smartgraph.graph.GraphEdgeList.insertVertex(GraphEdgeList.java:139)
	at application.MainApp_Layout.retrieveRelationships(MainApp_Layout.java:612)

I am adding the vertices in this way
for (int i = 0; i < Influence_relation.getLength(); i++) {
			Node inner_node = Influence_relation.item(i).getFirstChild();
					FTGgraph.insertVertex(inner_node.getNodeValues());

}

**Comment by brunomnsilva** [comment]
Thanks! 

That topic has been discussed in:

#8 

Using that overloaded method a vertex will be inserted with that element. In your situation you're attempting to insert more than one vertex containing the same "element". Those vertices must be differentiated somehow, see the discussion in #8. 

Feel free if you need further assistance.
