### ISSUE TITLE
The Arrow direction is not working properly. Every time the arrow direction change by itself.

### ISSUE THREAD

**Issue by manzoorhussain1996** [brunomnsilva/JavaFXSmartGraph#18]
Hi,
Once again I thank you for this nice graph library. I run your own example but when I run it, the arrow itself changes the direction .If I set the arrow like this 
A->B and B->A 
then the arrow always headed to B like A->B in both cases.
The other problem
When I run this example 
g.insertVertex("A");
g.insertVertex("B");
g.insertVertex("C");
g.insertVertex("D");
g.insertVertex("E");
g.insertVertex("F");
g.insertVertex("G");

g.insertEdge("A", "B", "1");
g.insertEdge("A", "C", "2");
g.insertEdge("A", "D", "3");
g.insertEdge("A", "E", "4");
g.insertEdge("A", "F", "5");
g.insertEdge("A", "G", "6");

the arrow head is not heading toward source and target. For example the edge arrow of vertices connected to A is not correct only A->F is connected in correct way. Also the vertices connected to H are not connected correct way lets say the arrow should to toward I in H->I and H->J.

Also It changes every time when I run the application.
 Please give some solution. I am working some research work and I want to use this library to show my data.
Thank you
![image](https://user-images.githubusercontent.com/58062708/88394125-d312d900-cdf9-11ea-8eca-4badc14735b3.png)
![image](https://user-images.githubusercontent.com/58062708/88396168-220e3d80-cdfd-11ea-9ced-06c9c7042b48.png)

**Comment by manzoorhussain1996** [comment]
> Hi,
> Once again I thank you for this nice graph library. However, the path for A->B and B->A is same. For example in the first case
> A is source and B is target
> so the arrow should be A->B.
> In second case B source and A is target
> the arrow should be B->A.
> In your example the error is same as F->D ad D->F, the arrow is always F to D. Can you please tell me any solution for this problem.
> Thank you
> ![image](https://user-images.githubusercontent.com/58062708/88363602-8f00e380-cdbb-11ea-903e-a8d259ef488a.png)
> ![image](https://user-images.githubusercontent.com/58062708/88363693-ca031700-cdbb-11ea-98d9-2e5033d8e170.png)

Also every time the arrow direction change when there is  A->B, and B->A relationship.

**Comment by brunomnsilva** [comment]
Hi again,

Well, if you want a directed graph, you **must** use a graph implementation that supports directed edges, e.g., a `Digraph` implementation.

The provided example uses this:

```java
private Graph<String, String> build_sample_digraph() {

        Digraph<String, String> g = new DigraphEdgeList<>();

        g.insertVertex("A");
        g.insertVertex("B");
        g.insertVertex("C");
        g.insertVertex("D");
        g.insertVertex("E");
        g.insertVertex("F");

        g.insertEdge("A", "B", "AB");
        g.insertEdge("B", "A", "AB2");
        g.insertEdge("A", "C", "AC");
        g.insertEdge("A", "D", "AD");
        g.insertEdge("B", "C", "BC");
        g.insertEdge("C", "D", "CD");
        g.insertEdge("B", "E", "BE");
        g.insertEdge("F", "D", "DF");
        g.insertEdge("F", "D", "DF2");

        //yep, its a loop!
        g.insertEdge("A", "A", "Loop");

        return g;
    }
```
Simple fix, then :smiley:

**Comment by manzoorhussain1996** [comment]
Wow!
@brunomnsilva generous of  you. Thank you I just fix now. Thank you for quick support.

**Comment by manzoorhussain1996** [comment]
Hi
Can we change the arrow color with edge styling? For example I change the Edge color but the arrow color is still the default one.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by brunomnsilva** [comment]
Yes, but you must use the corresponding "style" for the arrows in `smartgraph.css`:

```css
.arrow {
    -fx-stroke-width: 2;
    -fx-stroke: #FF6D66;  
    -fx-opacity: 0.8;
}
```

**Comment by manzoorhussain1996** [comment]
Thank you Bruno,
But I have four relationship type and I need to represent it by color. For example relation A’s edge color is green and relationship B’s edge color is yellow ….so on. I want to change the arrow color as well.for example for all A type relationship the edge color and arrow color should be green. For All B type relationship the edge color and arrow should yellow. So how can I do that?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by brunomnsilva** [comment]
To set styles individually (vertices or edges) the only way is programatically. The `Main` method contains an example, as so below:

```java

SmartStylableNode stylableEdge = graphPanel.getStylableEdge(/* two versions of this method, check docs*/);

stylableEdge.setStyle("-fx-stroke: yellow; -fx-stroke-width: 2;"); //e.g., yellow or #FF0000 hex code

```

As for the arrows, *in the current version* there is no way to do this; it will only allow the same style for all arrows. Sorry!

**Comment by manzoorhussain1996** [comment]
Thank you for time. I spent lot of time to find a way. But I could only change the edge color and vertex not the arrow. I really appreciate your work and passion. Thank you for this lovely library.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by brunomnsilva** [comment]
At this time I won't be implementing this, but you can can change the source and succeed in it, I believe (untested!):

1. E.g., override `setStyle` (currently using default implementation of javaFX) method in `SmartGraphEdgeLine` and `SmartGraphEdgeCurve`;

2. In the above implementation, while maintaining the expected behavior for the edge, call `getAttachedArrow` method (which returns a `Shape` descendent) and you will be able to set the same style to the connected arrow.

Or, if you're using, e.g., `setStyleClass` methods, append step 2 to the current implementation.

Does this help?

**Comment by manzoorhussain1996** [comment]
I will try sir. I need this implementation.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
