### ISSUE TITLE
Dinamically change vertex's label.

### ISSUE THREAD

**Issue by LazyAfternoons** [brunomnsilva/JavaFXSmartGraph#19]
Hello and thank you for your hard work on this library. This is more of a question than an issue. I was wondering if I could change a vertex's label in my custom _Strategy_ class or even outside it. 
I was looking at the javadoc and eventually I found out that I can load my custom CSS class by using the _setStyleClass_ method on a _SmartLabel_ object. This _SmartLabel_ is attached to a _SmartGraphVertextNode_ in the _addVertex_ method in _SmartGraphPanel_. 
I can't find a way to get this _SmartLabel_ and load the CSS class into it. 
Any help is deeply appreciated, thank you.

**Comment by brunomnsilva** [comment]
This was already answered in previous issues.

The labels are automatically pulled from the contained element's `toString()` method. If you update the state of the element's instance and call `GraphPanel.update()` it will reload the labels.

**Comment by brunomnsilva** [comment]
This is now possible. Believe I misunderstood your issue from the beginning.

**Comment by LazyAfternoons** [comment]
Sorry for the late answer and thank you again for your work.
