### ISSUE TITLE
Question : new style of Vertex / Edge

### ISSUE THREAD

**Issue by thomakl** [brunomnsilva/JavaFXSmartGraph#2]
Hi,

First of all, thank you for you work - it's great.

I'm working with your project and I need to create a new method to apply a different style of Edges and Vertexes. I was thinking of creating property in the "_smartgraph.css_" and then create a new method of inserting an element like the "_insertVertex(...)_" method.
The issue is the link from a property in _smartgraph.css_ and _insertVertex()_ is more deep than expected.

Do you see an easy way to do it ? Or should I modify / create a method for each file in the process ?

Thank you for your time,

TL

**Comment by brunomnsilva** [comment]
Thanks! :smile:

Are you talking about applying different styles among, e.g., vertices?

You can use `graphView.getStylableVertex("A").setStyle("-fx-fill: gold; -fx-stroke: brown;");` for that, but I believe you want to specify in the smartgraph.css other styles and later choose which one to apply?

I think that can be accomplished by adding (and then implementing) that behavior to `SmartStylableNode`. 

If I'm right I can try it!

**Comment by brunomnsilva** [comment]
You now have the `setStyleClass(String cssClass)` method available. See the README for example.
