### ISSUE TITLE
Graph.removeEdge() removes the visual edge but the attraction remains

### ISSUE THREAD

**Issue by madhephaestus** [brunomnsilva/JavaFXSmartGraph#22]
To reporduce:

Add 2 vertexs A and B. Make a link between them.

In code later make a new vertex C and then add an edge to A. 

In code later remove the C to A edge with g.removeEdge(name) 

 graphView.update();

Observe that the arrow is removed, but the attraction between C and A remains.

**Comment by brunomnsilva** [comment]
@madhephaestus You're right! :+1: I think it's fixed now. 

The forces were only correctly recomputed with vertex removal. Now it works as expected for edges also. Thanks for pointing it out!

**Comment by madhephaestus** [comment]
Wow, fixed so fast! you rock @brunomnsilva !

I tested your fix, it works perfectly as expected now. What a fantastic library you have here!
