### ISSUE TITLE
[Feature Add] It would be nice if a gradle configuration was supported

### ISSUE THREAD

**Issue by madhephaestus** [brunomnsilva/JavaFXSmartGraph#23]
Using this project as a gradle sub-module would be a very useful feature. To add support for that a build.gradle file needs to be added, and the resources need to be moved into a directory.

**Comment by CasparNuel** [comment]
For anyone who wants to include this library in their gradle.build file but does not know how,
you can include it in your project like this. It will not be a sub-module but you will be able to use it in your code.

Add the following to your build.gradle:

```
repositories {
    flatDir {
    dirs '<path-to-directory-where-you-stored-the-jar>'
    }
}

dependencies {
    implementation name:'JavaFXSmartGraph-x.x.x', ext:'jar'
}
```

Where you replace `<path-to-directory-where-you-stored-the-jar>` with the absolute path of the **directory** where the library is stored, and `x.x.x`with the version of JavaFXSmartGraph you have as a jar.

**Comment by brunomnsilva** [comment]
It's now available at Maven Central (see README). It should be easily integrated into a Gradle build.
