### ISSUE TITLE
Do update works with SmartCircularSortedPlacementStrategy?

### ISSUE THREAD

**Issue by FernandoLomazzi** [brunomnsilva/JavaFXSmartGraph#26]
Do SmartGraphPanel update() works with SmartCircularSortedPlacementStrategy?
When I make this code it works perfectly:
![image](https://user-images.githubusercontent.com/78239004/179455938-f08aa492-29dd-442d-8d25-0ac79f9a7404.png)
But if I do this, the graph not uses circular sorted placement:
![image](https://user-images.githubusercontent.com/78239004/179455985-4c285033-fea7-4367-8eb1-d137c02156bd.png)

**Comment by brunomnsilva** [comment]
Hi @Lascot29,

The *placement strategies* are one-shot vertex placements made at the `.init()` method. They are best used for static graphs. With this approach, any later nodes that are added can be manually placed by the programmer (see `setVertexPosition`).

Your second snippet adds the nodes after the `init()` call (here the 0 nodes are placed - therefore, no placement occurs). By memory, you should get all the nodes placed at the center, overlapped. Am i right?

**Comment by FernandoLomazzi** [comment]
Yes, ok I didn't know that.
One more thing, I made a university project with your library and I want to upload it to github. I have to mention your library in the repo and copy the lincese.txt?
Is my first project and I'm not familiar with copyright.

**Comment by brunomnsilva** [comment]
Yes, most open-source licenses just ask for "attribution". You can attain this with the inclusion of the file `LICENSE.txt`.
If you use other libraries, you can place all the licenses' text in the same file, identifying the name of each library.
