### ISSUE TITLE
method g.replace(e, newElement) with graphView.update() is not updating the graph

### ISSUE THREAD

**Issue by thomakl** [brunomnsilva/JavaFXSmartGraph#3]
Hi, 

I used your method from your project at Main.java : 
`graphView.setVertexDoubleClickAction(graphVertex -> {
            System.out.println("Vertex contains element: " + graphVertex.getUnderlyingVertex().element());
            g.replace(graphVertex.getUnderlyingVertex(),"NewEntity");
            System.out.println("Vertex contains element: " + graphVertex.getUnderlyingVertex().element());
            graphView.update();
        });`

I added the instruction ` g.replace(graphVertex.getUnderlyingVertex(),"NewEntity");`
When I ask the name of this current vertex, the method changed its name but even after the instruction of updating the graphView, it doesn't show the new name.

**Comment by brunomnsilva** [comment]
Thanks for the heads up! The latest commit now ensures all labels are updated.
That was simply not being done.
