### ISSUE TITLE
Question: is it possible to use different shapes for vertices?

### ISSUE THREAD

**Issue by SashaVolushkova** [brunomnsilva/JavaFXSmartGraph#37]
I see , that i can use css for change  color, or label font. But it will be more better to use different shapes for different types of vertices. Is it possible? Thanks!

**Comment by k1ll1n** [comment]
This question has already been asked by the community, but there is no answer to it.
https://github.com/brunomnsilva/JavaFXSmartGraph/issues/4

I’ll add on my own that I also tried replacing the vertices with some icons, which was also unsuccessful(
https://github.com/brunomnsilva/JavaFXSmartGraph/issues/34

For this reason, we are waiting for a response from the author of the project.

**Comment by brunomnsilva** [comment]
Hi! This "request" is not new, but it needs some (maybe heavy) changes to the base code. 
I just released version 1.1 with minor improvements. I'll try to tackle this in the following days and see what can be done without straying from the library's main objective -> to visualize an underlying model. 

Can you share with me your use cases, so I can have some direction?

**Comment by k1ll1n** [comment]
Hello @brunomnsilva! I'm planning to generate a map of geographic locations based on your JavaFXSmartGraph. Therefore, I need the ability to replace vertices with icons (svg or png) of cities and villages (perhaps some other options).

This is my use case for your JavaFXSmartGraph)

**Comment by SashaVolushkova** [comment]
@brunomnsilva , Hello! 
Cases:
I use this tool to show event graph: services, events(as edges), topics. And I need to differ services and topics. Now I use css, but it will be nice to choose icon by some parameter in Vertex ( Graph<**V**, E>). 

If you  have any ideas, how to make it possible, I'll try to help (and try to make PR). 

Thanks.

**Comment by brunomnsilva** [comment]
New shapes added to version 2.0.0-rc1! 😄 

Regarding images, maybe they can be set to the background of the shapes. I'll have to look into it!

**Comment by brunomnsilva** [comment]
Closing this issue, as resolved. 

For the background of shapes, see issue #34.
