### ISSUE TITLE
Question: is it possible to insert labels inside vertices?

### ISSUE THREAD

**Issue by lorenzodbr** [brunomnsilva/JavaFXSmartGraph#38]
In all the examples provided, labels were placed outside their vertices. I was wondering if they could be put within them. Thanks

**Comment by lorenzodbr** [comment]
Solved it by adding a new property in `.properties` file (namely `vertex.label-inside`); then added a boolean field in `SmartGraphVertexNode` used in `attachLabel` & `boundVertexNodeYPositioning` methods to set the label position. Not sure if any other changes are needed (for instance, with different shapes).

**Comment by brunomnsilva** [comment]
Hi, @lorenzodbr .

Yes, the only way is to delve into the implementation. 
I never considered that possibility, since most of the times the labels would expand beyond the boundaries of the vertices.

**Comment by SashaVolushkova** [comment]
thanks for this feature! It will help me to develop my project: https://github.com/AxenAPI/axenapi-ui/tree/develop?tab=readme-ov-file
