### ISSUE TITLE
Question : alternative shapes than circles ?

### ISSUE THREAD

**Issue by thomakl** [brunomnsilva/JavaFXSmartGraph#4]
Hi,

Are you planning to implement a way to create new shapes in the graph like boxes or ellipses ?

**Comment by brunomnsilva** [comment]
I can look into it! :wink: 

But, since it will take some effort, I can only try to do it by next month.

**Comment by chuckdu21** [comment]
any news ?

**Comment by jameshball** [comment]
Just a +1 on this, it would be amazing to be able to get custom vertices so that I could render any JavaFX Pane as the vertex. Is this possible @brunomnsilva ?

**Comment by brunomnsilva** [comment]
New shapes added to version 2.0.0-rc1! 😄
