### ISSUE TITLE
Question: are there plans to make this available through Maven?

### ISSUE THREAD

**Issue by pedrovictori** [brunomnsilva/JavaFXSmartGraph#5]
Hello, thank you very much for making this available, it is really useful.
I'm using it in a Maven project, and it would be very convenient to have it available through a Maven repository. Do you have any plans for this? If not, that's completely fine, I was just wondering. 
Thank you!

**Comment by brunomnsilva** [comment]
Seems very pertinent to do that.

However, I need to search how to best synchronize the sources here with a maven repository, as I haven't done that before.

Is there a simple way to refer maven artifacts to the contents of the `release` folder here on GitHub?

**Comment by pedrovictori** [comment]
Sorry I didn't reply sooner. You can set up something like [this](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-apache-maven-for-use-with-github-packages), so you host them as GitHub packages and deploy from Maven. You could also set a GitHub [workflow](https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow) so the package is automatically deployed with every new release. I recently did that for one of my repositories and it is a fairly simple process. I'm happy to help if needed.

**Comment by amalic** [comment]
@brunomnsilva Check out this Github tutorial --> [Publishing packages to GitHub Packages](https://docs.github.com/en/actions/guides/publishing-java-packages-with-maven)

**Comment by brunomnsilva** [comment]
Finally! 😄  Here it is:

```xml
<dependency>
    <groupId>com.brunomnsilva</groupId>
    <artifactId>smartgraph</artifactId>
    <version>1.0.0</version>
</dependency>
```
