### ISSUE TITLE
Can't add edges with the same name

### ISSUE THREAD

**Issue by sansarip** [brunomnsilva/JavaFXSmartGraph#8]
Expected behavior:

Two edges should be able to exist with the same name. And by name, I really mean label.

[![Image from Gyazo](https://i.gyazo.com/41ce9d8f7f288899cce3a91be834a8e2.png)](https://gyazo.com/41ce9d8f7f288899cce3a91be834a8e2)

Actual behavior:

If I try to make the graph displayed above, then an error is thrown claiming that the edge `a` already exists.

```java
com.brunomnsilva.smartgraph.graph.InvalidEdgeException: There's already an edge with this element.
	at com.brunomnsilva.smartgraph.graph.DigraphEdgeList.insertEdge(DigraphEdgeList.java:99)
```

Perhaps there should be an additional `label` parameter available to edge objects, and that `label` is what should be displayed instead of the edge key?

e.g.

```java
g.insertVertex("start", "state a", "a", "a")
g.insertVertex("state b", "state a", "a2", "a")
```

You could also just auto-generate a unique-enough edge key by combining the inbound-vertex, outbound-vertex, and label.

e.g.

```java
// behind the scenes the key would be something like "start, state a, a" <- could hash this
g.insertVertex("start", "state a", "a")

// "state b, state a, a"
g.insertVertex("state b", "state a", "a")

// the visual label would be a for both
```

**Comment by sansarip** [comment]
The solution is to create a class that overrides the equality functions, and use that as the edge

```java
private class EdgeLabel {
        String inboundEdge;
        String outboundEdge;
        String label;

        EdgeLabel(String outboundEdge, String inboundEdge, String label) {
            this.outboundEdge = outboundEdge;
            this.inboundEdge = inboundEdge;
            this.label = label;
        }

        @Override
        public int hashCode() {
            return new HashCodeBuilder(17, 31).
                    append(inboundEdge).
                    append(outboundEdge).
                    append(label).
                    toHashCode();
        }

        @Override
        public boolean equals(Object obj) {
            if (!(obj instanceof EdgeLabel))
                return false;
            if (obj == this)
                return true;

            EdgeLabel other = (EdgeLabel) obj;
            return new EqualsBuilder().
                    append(inboundEdge, other.inboundEdge).
                    append(outboundEdge, other.outboundEdge).
                    append(label, other.label).
                    isEquals();
        }

        @Override
        public String toString() {
            return label;
        }
    }
```

and then 

```java
g.insertEdge(outBound, inBound, new EdgeLabel(outBound, inBound, edgeLabel));
```

**Comment by brunomnsilva** [comment]
Hi @sansarip .

That is something that can also be taken care of in the class used as the Edge's generic type -- to override the "equals" method. 

What is shown in the label is just the "toString" of that same class, whereas you can have more attributes used to differentiate the "equals".

**Comment by thomakl** [comment]
Hi @brunomnsilva,

What would you recommend doing to overcome this label 'issue' ?

**Comment by brunomnsilva** [comment]
I have previously addressed this, but I'll give an example.

The provided graph implementations do not allow duplicate vertices and edges. The equality of the underlying objects is tested by the 'equals' method. 

The labels for vertices and labels come from the underlying element's 'toString' method. 

Hence, the solutions are the following:

* create your own graph implementation that would allow duplicates (harder), or;

* distinguish internally your objects that are contained within edges (easier and example follows).

Regarding the later, your edge object can look like this:

```java
public class EdgeObject {
    private static int counter = 1;
    private String name;
    private int innerId ;

    public EdgeObject(String name) {
        this.name = name;
        this.innerId = counter++;
    } 

    @override
    //equals 

    @override
    //toString 
} 
```
